### ISSUE TITLE
DevTools connection

### ISSUE THREAD

**Issue by JohnPaulHarold** [pinqy520/revas#3]
Have you investigated DevTools integration at all? (https://github.com/facebook/react/tree/e316f785526e503eceed1ae33b7a06440084b9c9/packages/react-devtools)

I've wired in some basic DevTools in a branch, and with it you can see something like this

<img width="898" alt="Screenshot 2021-02-07 at 15 20 17" src="https://user-images.githubusercontent.com/9934306/107151109-ce0e1500-6958-11eb-9001-ab3b5a75c0d8.png">

In that, you can see that I adjust the style prop to align `flex-end`

There's various issues with it, such as `<Text/>` components are not queryable, and not all props trigger changes. The new fiber based DevTools are also problematic with class based components it seems.

That all being said, it's _something_, or a start at least. The branch is over at https://github.com/JohnPaulHarold/revas/tree/devtools. I can make a PR if you want.

**Comment by pinqy520** [comment]
Great, I haven't investigated DevTools, welcome to make this PR, I will try to fix other issues later.

**Comment by JohnPaulHarold** [comment]
@pinqy520 hey, could you possibly publish a new version of `revas` with the devTools integration?

**Comment by pinqy520** [comment]
Done
